name: Infection
version: '2.0.0'
main: net.kalbskinder.infection.Infection
description: A plugin that adds a fun and competitive infection minigame
api-version: '26.1'
author: Kalbskinder

permissions:
  infection.join:
    description: Allows a player to run '/infection join <map-name>'
    default: true
  infection.leave:
    description: Allows a player to run '/infection leave'
    default: true
  infection.admin:
    description: Allows a player to access all of the '/infection <args>' commands.
    default: op
